#!/bin/sh
# https://opensource.org/licenses/MIT (c) 2017
# Oren Tirosh <oren.tirosh@compassnetworks.com>
#
# Add date in rfc-3339 format to output of git-branch or git-tag command.
# Suitable for piping into sort(1).

dateof() {
    git log --pretty=format:%ci --no-walk $1 2>/dev/null
}

cmd=${0##*git-}
git ${cmd%-date} "$@" | while read line; do
  ref=$(echo ${line#\*})
  printf "%-025s\t%s\n" "$(dateof $ref)" "$line"
done
