#!/bin/sh
# Oren Tirosh <oren.tirosh@compassnetworks.com>
# https://opensource.org/licenses/MIT (c) 2017
#
# Execute a command at the top directory of the git worktree

test ! -x "$(command -v "$1")" || set -- exec "$@"

case $(git rev-parse --is-inside-work-tree) in
    true)  TOP="$(git rev-parse --show-toplevel)" ;;
    false) TOP="$(git rev-parse --git-dir)/.." ;;
    *) exit 1;;
esac

cd "$TOP" && "${@:-pwd}"
